"""Parse and inspect skeleton.txt blocks generated by the skeleton pipeline.

Usage:
    # Default path (google/adk-python):
    DATA_DIR=$(pwd)/data PYTHONPATH=$(pwd) python3 scripts/test_skeleton.py

    # Custom skeleton file:
    DATA_DIR=$(pwd)/data PYTHONPATH=$(pwd) python3 scripts/test_skeleton.py data/<org>/<repo>/.analysis/skeleton.txt

    # Adjust log verbosity:
    python3 scripts/test_skeleton.py data/google/adk-python/.analysis/skeleton.txt --log-level DEBUG

    # List all nodes sorted by number of callees:
    DATA_DIR=$(pwd)/data PYTHONPATH=$(pwd) python3 scripts/test_skeleton.py data/google/adk-python/.analysis/skeleton.txt --nodes
    DATA_DIR=$(pwd)/data PYTHONPATH=$(pwd) python3 scripts/test_skeleton.py data/google/adk-python/.analysis/skeleton.txt --nodes --min_callees 5

    # Inspect call graph for a specific entity:
    DATA_DIR=$(pwd)/data PYTHONPATH=$(pwd) python3 scripts/test_skeleton.py data/google/adk-python/.analysis/skeleton.txt --entity src.google.adk.tools.skill_toolset.run_async
    DATA_DIR=$(pwd)/data PYTHONPATH=$(pwd) python3 scripts/test_skeleton.py data/google/adk-python/.analysis/skeleton.txt --entity src.google.adk.tools._google_credentials.get_valid_credentials
    DATA_DIR=$(pwd)/data PYTHONPATH=$(pwd) python3 scripts/test_skeleton.py data/google/adk-python/.analysis/skeleton.txt --entity src.google.adk.tools.pubsub.message_tool.publish_message
    DATA_DIR=$(pwd)/data PYTHONPATH=$(pwd) python3 scripts/test_skeleton.py data/google/adk-python/.analysis/skeleton.txt --entity src.google.adk.tools.openapi_tool.auth.auth_helpers.token_to_scheme_credential
    DATA_DIR=$(pwd)/data PYTHONPATH=$(pwd) python3 scripts/test_skeleton.py data/google/adk-python/.analysis/skeleton.txt --entity src.google.adk.memory.vertex_ai_rag_memory_service.search_memory
"""

import argparse
import json
import logging
import re
from pathlib import Path

import yaml

from src.py_summarizer.code_graph import CallEdge, build_call_graph

logger = logging.getLogger(__name__)


def split_blocks(text: str) -> list[str]:
    return [block.strip() for block in re.split(r"\n\s*\n+", text) if block.strip()]


def parse_block(block: str) -> dict | None:
    try:
        parsed = yaml.safe_load(block)
        return parsed if isinstance(parsed, dict) else None
    except yaml.YAMLError as error:
        logger.warning("Failed to parse YAML block: %s", error)
        return None


def preview_value(value, max_len: int = 120) -> str:
    text = str(value).replace("\n", " ").strip()
    if len(text) <= max_len:
        return text
    return text[: max_len - 3] + "..."


def read_skeleton_parts(file_path: Path, verbose: bool = False) -> None:
    text = file_path.read_text(encoding="utf-8", errors="ignore")
    blocks = split_blocks(text)

    parsed_count = 0
    for index, block in enumerate(blocks, start=1):
        parsed = parse_block(block)
        if parsed is None:
            if verbose:
                logger.info("Block %d: skipped (not a dict)", index)
            continue

        parsed_count += 1
        if verbose:
            fields = list(parsed.keys())
            logger.info("Block %d fields: %s", index, ", ".join(fields))
            for field_name in fields:
                logger.info("  %s: %s", field_name, preview_value(parsed[field_name]))

    logger.info("Parsed dict blocks: %d/%d", parsed_count, len(blocks))


def load_nodes_by_callees(graphs_path: Path) -> list[tuple[str, int]]:
    """Return all call graph nodes sorted by number of callees descending."""
    data = json.loads(graphs_path.read_text(encoding="utf-8"))
    edges = [
        CallEdge(source=e["source"], target=e["target"], type=e["type"])
        for e in data["call_graph"]["edges"]
    ]
    graph = build_call_graph(edges)
    nodes = [(n, graph.out_degree(n)) for n in graph.nodes()]
    return sorted(nodes, key=lambda x: x[1], reverse=True)


def load_call_graph_analysis(graphs_path: Path, entity_name: str) -> dict:
    """Load graphs.json and return input/output nodes for the given entity.

    Args:
        graphs_path: Path to .analysis/graphs.json
        entity_name: Function or module name to inspect in the call graph.

    Returns:
        Dict with keys 'entity', 'inputs' (callers), 'outputs' (callees).
    """
    data = json.loads(graphs_path.read_text(encoding="utf-8"))
    edges = [
        CallEdge(source=e["source"], target=e["target"], type=e["type"])
        for e in data["call_graph"]["edges"]
    ]
    graph = build_call_graph(edges)
    inputs = list(graph.predecessors(entity_name)) if entity_name in graph else []
    outputs = list(graph.successors(entity_name)) if entity_name in graph else []
    return {"entity": entity_name, "inputs": inputs, "outputs": outputs}


def print_graph_analysis(analysis: dict) -> None:
    entity = analysis["entity"]
    inputs = analysis["inputs"]
    outputs = analysis["outputs"]
    logger.info("=== Call Graph: %s ===", entity)
    logger.info("Callers  (inputs,  %d): %s", len(inputs), ", ".join(inputs) or "none")
    logger.info("Callees  (outputs, %d): %s", len(outputs), ", ".join(outputs) or "none")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Parse skeleton.txt blocks as YAML and log parsed fields."
    )
    parser.add_argument(
        "file_path",
        nargs="?",
        default="data/google/adk-python/.analysis/skeleton.txt",
        help="Path to skeleton file (default: data/google/adk-python/.analysis/skeleton.txt)",
    )
    parser.add_argument(
        "--nodes",
        action="store_true",
        help="List all call graph nodes sorted by number of callees descending.",
    )
    parser.add_argument(
        "--min_callees",
        type=int,
        default=0,
        help="Filter --nodes output to nodes with at least this many callees (default: 0).",
    )
    parser.add_argument(
        "--entity",
        default=None,
        help="Function or module name to inspect in the call graph.",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
        help="Logging level",
    )
    args = parser.parse_args()

    logging.basicConfig(level=getattr(logging, args.log_level), format="%(levelname)s: %(message)s")

    file_path = Path(args.file_path)
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")

    graphs_path = file_path.parent / "graphs.json"
    if args.nodes:
        if not graphs_path.exists():
            logger.warning("graphs.json not found at %s", graphs_path)
            return
        for node, out_deg in load_nodes_by_callees(graphs_path):
            if out_deg >= args.min_callees:
                logger.info("callees=%d  %s", out_deg, node)
    elif args.entity:
        if not graphs_path.exists():
            logger.warning("graphs.json not found at %s", graphs_path)
            return
        analysis = load_call_graph_analysis(graphs_path, args.entity)
        print_graph_analysis(analysis)
    else:
        read_skeleton_parts(file_path)
        if graphs_path.exists():
            logger.info("Pass --entity <name> to inspect a node in the call graph")
        else:
            logger.warning("graphs.json not found at %s — skipping call graph analysis", graphs_path)


if __name__ == "__main__":
    main()
